# Generated by Django 5.1.4 on 2024-12-09 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_create_initial_departments'),
    ]

    operations = [
    ]
